### ISSUE TITLE
Master Coordination Issue for Sprints

### ISSUE THREAD

**Issue by eah13** [skulpt/skulpt#400]
Who's working on what and how do we prioritize specific features?  How will new contributors understand what would be most helpful to work on? This issue, that's how :sunglasses: 

Building off of the project management goodness of issues like #290 and #297, this is a list of scopes of work linking off to issues and/or pull requests dealing with those items. It's an index of sorts. 

If you're working on these features or interesting in working on them, please comment below or tag this issue so I can keep it updated. Thanks to everyone who contributed to the Google Doc that this started life as, including @LeszekSwirski @waywaaard @gerbal and @albertjan.

There shouldn't be too many collisions or duplicated work.  If you're worried about that, request that @bnmnetp assign you to an issue if you want people to know you're working on it. Better yet, open that pull request early so others can see what you're doing!

### Built-ins
- [ ] High: built-in class inheritance.  Issue #213
- [ ] complex()
- [ ] dict() does not support **kwargs
- [ ] eval() 
- [ ] .format()
- [ ] help(). Discussion: #249
- [ ] iterable methods. Issues: #282 and possibly #338, #335, 
- [ ] max/min don't support key arguments. Issue: #393
- [ ] open() modes. 
- [ ] property() #326 
- [ ] reversed()
- [ ] Try/except/finally
- [ ] type() Issue #97
- [ ] unichr()
- [ ] variable operators check
   - [ ] It seems some variable operators are behaving strangely (see #278). Worth a check
- [ ] With statement

### Stdlib
- [ ] calendar
- [ ] cmath. #387 may lay groundwork
- [ ] collections
- [ ] __future__. Discussion: #313
- [ ] itertools
- [ ] keyword
- [ ] math (math.degrees and math.sqrt are missing.  module needs an audit.) #math
- [ ] sys, os & argparse compatibility/overrides
   - [ ]  __platform__ (prereq to sys). Notes: #397
   - [ ] sys Issue: #300, #269 Notes:  #398
- [ ] urllib2
- [ ] urlparse  https://docs.python.org/2/library/urlparse.html
- [ ] textwrap Issue: #261
- [ ] time & datetime Issue: #243
- [ ] xml Issue: #289 

### Third Party Modules
- [ ] finish/add to numpy & matplotlib Notes: #399
- [ ] pandas
- [ ] TKinter  

### Performance/under-the-hood
- [ ] More Pervasive use of Suspensions
  - [ ] More performant 'debug mode'
- [ ] V8 Optimizations. Issue: #295
- [ ] Emscripten Experiments.  Discussion: #246

**Comment by dsblank** [comment]
Can you add `processing` to the list of 3rd-party modules? There are some big and small issues there, and I'd be glad to help orchestrate any sprint, and long distance work on it. Thanks!

**Comment by eah13** [comment]
@dsblank Awesome!  Added and you're listed as PRP.  Open a PR whenever you start on it (you can say not ready for merge) and I'll link to that too.  Quite a few requests/issues about that module

**Comment by eah13** [comment]
@Jacco saw in gitter you're working on `datetime`.  No pressure, but the PRP spot for that module is open :)  Let me know if you're the one for the job.

**Comment by Jacco** [comment]
Well I started on it. Thinking it would be a nice experience to learn
skulpt on the way. So I started making a javascript impementation first.
Then I stumbled on the cpython libraries where I found the datetime module.
It appears to be a much better road to follow. But starting in that
direction I ran into hard problems like decorators and other currently
unsupported stuff. And those things are too hard for me to implement in
skulpt unfortunately.

Regards Jacco

**Comment by waywaaard** [comment]
Are those property decorators or abstract method decorators? I think most people would be ok to only use 30-50 % of the functionality rather than having none.

**Comment by bnmnetp** [comment]
@waywaaard,

I am in 100% agreement.  Having some of the core functionality in datetime is better than none.

The pure python implementation in pypy, I'm assuming thats what @Jacco is looking at, are for classmethods and making read-only properties.  I think it is not too hard to work around both of these.  (If I really had the time to dig in, getting decorators to work would be great.)   The other question is the use of the struct module, which is pretty limited in use, and could be avoided by leaving out those functions initially.

**Comment by Jacco** [comment]
https://github.com/python/cpython/blob/master/Lib/datetime.py

These are a few of the issues I ran in to:

__slots__ = '_days', '_seconds', '_microseconds', '_hashcode'

@property

@classmethod

different kind of constructors:
def __new__(cls, year, month=None, day=None, hour=0, minute=0, second=0,
microsecond=0, tzinfo=None):

**Comment by abdounasser202** [comment]
i'v tried it on my chrome app but it's does'nt work! Please can you tell me how can i create a chrome app in pure python?

**Comment by waywaaard** [comment]
I guess we can check a few of those boxes now.

**Comment by waywaaard** [comment]
unichr() has been implemented in a PR
math.degrees and math.sqrt are in the math module

**Comment by albertjan** [comment]
@waywaaard updated the issue :)

**Comment by waywaaard** [comment]
type() Issue #97 has been already fixed by PR #329

**Comment by j-f1** [comment]
The `keyword` module seems to have been implemented.
